---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: MARIADB
  generation: 13
  name: mariadb
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a databse.
      iconClass: icon-mysql-database
      openshift.io/display-name: MYSQL Latest
      tags: mysql,mariadb,maria
    from:
      kind: DockerImage
      name: docker.io/oondeo/mariadb:latest
    importPolicy: {}
    name: "latest"
    referencePolicy:
      type: Source
  - annotations:
      description: Provides a databse.
      iconClass: icon-mysql-database
      openshift.io/display-name: MYSQL Latest
      tags: hidden,mysql,mariadb,maria,mariadb-10.2,mariadb-10
      version: "10.2"
    from:
      kind: DockerImage
      name: quay.io/oondeo/mariadb:10.2
    importPolicy: {}
    name: "10.2"
    referencePolicy:
      type: Source
---
apiVersion: v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/display-name: MYSQL
  name: mysql
  namespace: openshift
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations:
      description: Provides a databse.
      iconClass: icon-mysql-database
      openshift.io/display-name: MYSQL Latest
      tags: mysql,mariadb,maria
    from:
      kind: DockerImage
      name: docker.io/oondeo/mariadb:latest
    importPolicy: {}
    name: "latest"
    referencePolicy:
      type: Source
  - annotations:
      description: Provides a databse.
      iconClass: icon-mysql-database
      openshift.io/display-name: MYSQL Latest
      tags: hidden,mysql,mariadb,maria,mariadb-10.2,mariadb-10
      version: "10.2"
    from:
      kind: DockerImage
      name: quay.io/oondeo/mariadb:10.2
    importPolicy: {}
    name: "10.2"
    referencePolicy:
      type: Source      
